table! {
    items (id) {
        id -> Integer,
        qu -> Text,
        zheng -> Text,
        url -> Text,
        name -> Text,
        huxing -> Text,
        floor -> Text,
        square -> Text,
        structs -> Text,
        inner_square -> Text,
        build_type -> Text,
        direction -> Text,
        build_year -> Text,
        build_decorate -> Text,
        build_struct -> Text,
        gongnuan -> Text,
        tihubi -> Text,
        dianti -> Text,
        quansu -> Text,
        guapai_time -> Text,
        yongtu -> Text,
        nianxian -> Text,
        fangquan -> Text,
        guapai_price -> Text,
        chengjiao_zhouqi -> Text,
        tiaojia -> Text,
        chengjiao_price -> Text,
        danjia -> Text,
    }
}
