table! {
    items (id) {
        id -> Integer,
        qu -> Text,
        zheng -> Text,
        url -> Text,
        name -> Text,
        huxing -> Text,
        floor -> Text,
        floor_number -> Integer,
        square -> Float,
        structs -> Text,
        inner_square -> Float,
        build_type -> Text,
        direction -> Text,
        build_year -> Integer,
        build_decorate -> Text,
        build_struct -> Text,
        gongnuan -> Text,
        tihubi -> Text,
        dianti -> Text,
        quansu -> Text,
        guapai_day -> Nullable<Date>,
        yongtu -> Text,
        nianxian -> Text,
        fangquan -> Text,
        guapai_price -> Integer,
        chengjiao_zhouqi -> Integer,
        tiaojia -> Integer,
        chengjiao_price -> Integer,
        chengjiao_day -> Nullable<Date>,
        danjia -> Integer,
    }
}
